input_file: "datasets/test.jsonl"
output_dir: "output_f"
text_field: "func"


algorithm: minhash
num_perm:  512         
ngram_size: 2       
bands: 128
threshold: 0.34
mode: "code"
use_semantic_lsh: False
# # model_name: "BAAI/bge-base-en-v1.5"
model_name: "BAAI/bge-small-en-v1.5"
threshold_semantic_lsh: 0.87

          
# algorithm: simhash
# ngram_size: 3     
# threshold: 20
# num_blocks: 8


# algorithm: semantic
# model_name: "BAAI/bge-small-en-v1.5"
# threshold: 0.87

# debug: false